### ISSUE TITLE
Display zero and negative AC

### ISSUE THREAD

**Issue by Attronarch** [SeamusFinlayson/Bubbles-for-Owlbear-Rodeo#112]
Hello! Right now AC of 0 and below does not display. It would be great if you could add that functionality for us who are still playing old-school D&D with descending AC. :)

**Comment by Attronarch** [comment]
Apologies, I've seen that's already an open issue! 

https://github.com/SeamusFinlayson/Bubbles-for-Owlbear-Rodeo/issues/64

**Comment by SeamusFinlayson** [comment]
I can enable negative AC fairly easily but 0 is tricky because that's my display nothing condition. I may add an optional toggle to enable this behavior actually. What version of D&D do you play, just so I can look into these rules a little bit?

**Comment by Attronarch** [comment]
Most of the TSR-era editions have AC -9 to 9 (and beyond). 

For example, AD&D 1e attack matrices:

![image](https://github.com/SeamusFinlayson/Bubbles-for-Owlbear-Rodeo/assets/71148475/34623054-7ce3-4a64-956f-7b5a2e213435)

D&D Rules Cyclopedia attack matrices:

![image](https://github.com/SeamusFinlayson/Bubbles-for-Owlbear-Rodeo/assets/71148475/f6b0bf50-653c-4c2f-b85c-8ab21c7e0bfa)

Reaching AC 0 or below isn't very difficult after PCs amass some wealth and magical armour. There are monsters with AC 0 as well.

**Comment by SeamusFinlayson** [comment]
Thanks for the resources I'll look into this.

**Comment by SeamusFinlayson** [comment]
This will not be added to Stat Bubbles for D&D. This extension targets 5e specifically. For this and other incompatible systems you should instead use Owl Trackers which is currently in development. More information is available on [Patreon](https://www.patreon.com/collection/420087?view=expanded), where you can follow along for updates.
