### ISSUE TITLE
Courier slash runs into numbers

### ISSUE THREAD

**Issue by Attronarch** [SeamusFinlayson/Bubbles-for-Owlbear-Rodeo#113]
See screenshot:

![Screenshot_20240110_103657](https://github.com/SeamusFinlayson/Bubbles-for-Owlbear-Rodeo/assets/71148475/dde99da0-f069-4e97-8310-52d1a1545437)

Token are set to have Courier font

**Comment by SeamusFinlayson** [comment]
What operating system are you using?

**Comment by SeamusFinlayson** [comment]
Try installing Lucidia Console font, that's what the default is, that might work as a temporary fix for you. I'll look into expanding the font family list though so this error doesn't come up again.

**Comment by SeamusFinlayson** [comment]
This should be fixed by the 1.7 update which switches the font to Roboto, this change is currently live in the dev channel: https://bubble-dev.onrender.com/manifest.json
