### ISSUE TITLE
Bloodied Condition

### ISSUE THREAD

**Issue by haamukahvi** [SeamusFinlayson/Bubbles-for-Owlbear-Rodeo#151]
Hey! I love this extension, super good work! I was wondering if it would make sense to vizualise the new Bloodied condition on creatures, showing a red circle / icon while its health is equal or less than half 🤔

**Comment by SeamusFinlayson** [comment]
I appreciate the suggestion. The extension already has a way to show bloodied and I'm not super interested in reimplementing it in this way. I have heard this suggestion before though so ill keep it in mind. 

If you want to pursue this yourself it wouldn't be too difficult to make another extension that reads the token metadata that this extension creates to generate the circles.
