### ISSUE TITLE
lack Initiative value and dice

### ISSUE THREAD

**Issue by yyzitai** [SeamusFinlayson/Bubbles-for-Owlbear-Rodeo#36]
Love this feature,If possible;
Suggestion: add Initiative value and dice.
The player has permission to throw.
It is best to add an Initiative tracker.

**Comment by yyzitai** [comment]
![20231105](https://github.com/SeamusFinlayson/Bubbles-for-Owlbear-Rodeo/assets/149901314/6b942964-7753-4d6c-b12e-427e63b28803)

**Comment by SeamusFinlayson** [comment]
Hi, the goal of this extension is only to track health and armor class in a very simple way. For those features I would recommend using Owlbear Rodeo's dice and initiative extensions.
